# Generated by Django 2.1.7 on 2019-06-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190617_1333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aexperts',
            unique_together=set(),
        ),
    ]
