# Generated by Django 2.1.7 on 2019-06-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190617_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ask_with_public',
            new_name='ask_with_only_experts',
        ),
    ]
