# Generated by Django 2.1.7 on 2019-08-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190617_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Mygroup'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('L', 'liked'), ('C', 'comment'), ('S', 'share'), ('F', 'follow'), ('G', 'share_to_group')], max_length=1),
        ),
    ]
