# Generated by Django 2.1.7 on 2019-08-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_group_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_profile',
            name='group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_for_profile', to='post.Mygroup'),
        ),
    ]
